import type { Metadata } from "next";
import localFont from "next/font/local";
import { Poppins } from 'next/font/google';
import  GT_Haptik  from "next/font/local";
import "./globals.css";

const poppins = Poppins ({
  subsets: ['latin'],
  weight: ['400'],
})

const spaceMono = GT_Haptik ({
  src: "./fonts/HK-Grotesk/HKGrotesk-Regular.otf",
})

const neueMachina = localFont({
  src: "./fonts/NeueMachina-Regular.otf",
  weight: "900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceMono.className} ${poppins.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
